spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.lzz.model
  mapper-locations: classpath:mapping/*Mapper.xml
server:
  port: 8081
